apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: testgo0128a 
  janus-idp.io/tekton: testgo0128a
  backstage.io/kubernetes-id: testgo0128a
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: testgo0128a
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  