apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: testgo0128a
  janus-idp.io/tekton: testgo0128a
  backstage.io/kubernetes-id: testgo0128a
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: testgo0128a
resources:
- deployment.yaml
- route.yaml
- service.yaml
