apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: testgo0128a
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: testgo0128a 
  name: testgo0128a
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: testgo0128a
    weight: 100 
